name: Update Changelog

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    name: Update Changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: 'docs: update CHANGELOG for ${{ github.event.release.tag_name }}'
          file_pattern: CHANGELOG.md
